### ISSUE TITLE
Subsequent import of basic.json displays errors

### ISSUE THREAD

**Issue by diger74** [Kentico/xperience-by-kentico-universal-migration-tool#76]
**Describe the bug**
When you import basic.json for the first time into empty database it is completed with no issues.
Though when you attempt to run it one more time, the same basic.json, it will show a few errors like this:

Cannot insert duplicate key row in object 'dbo.CMS_WebPageUrlPath' with unique index 'IX_CMS_WebPageUrlPath_WebPageUrlPathHash_WebPageUrlPathWebsiteChannelID_WebPageUrlPathContentLanguageID_WebPageUrlPathIsDraft'. The duplicate key value is (AA3543E5BD7D7DDDB1AE5F40C5AD0B9B7DE56583EF678C6C57E62F8662B729D8, 2, 4, 0).

**To Reproduce**
1. Restore the clean database
2. Import basic.json
3. Import basic.json one more time without restoring the database
4. Inspect the import log for errors

**Expected behavior**
Subsequent import of the same data should not produce errors.

**Library Version**
1.9.0

**Additional context**
Below is the log file containing these errors when I run it locally:
[import.log](https://github.com/user-attachments/files/17848287/import.log)

**Comment by akfakmot** [comment]
Hi @diger74 
fixed in 2.0.0.
Thanks for reporting.
